apiVersion: v1
kind: Service
metadata:
  name: platform-api-svc
  namespace: hashrace-game # 根据实际情况调整命名空间
spec:
  selector:
    app: platform-api
  ports:
    - protocol: TCP
      port: 3001 # 服务暴露的端口
      targetPort: 3001 # 容器实际监听的端口
  type: ClusterIP